channels:
- conda-forge
- omnia
dependencies:
- jupyterlab
- python
- nodejs
- ipython
- ipywidgets 
- notebook
- ipykernel
- nglview=2.1
- mdtraj
- openforcefield
- pip:
    - pytraj
    - sidecar
    - ipython_blocking
